sudo: required 
dist: trusty 
language: generic 
compiler:
  - gcc
env:
  matrix:
    - USE_DEB=true  ROS_DISTRO="indigo" PRERELEASE=true ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    - USE_DEB=true  ROS_DISTRO="indigo" PRERELEASE=true ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu
before_config:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - source .ci_config/travis.sh
  
