name: rig12_plate_controller

defaults:
  eds_pkg: ipa_canopen_test
  eds_file: "config/Whistle Gold V002.dcf"

modules:
  - name: rig1_plate_joint
    id: 1
  - name: rig2_plate_joint
    id: 85

     